version: '3'

services:
  redis:
    image: redis:5.0.3

  postgresql:
    image: postgresql:10.6
    volumes:
      - /opt/docker/containers/integration/postgres:/var/lib/postgresql/data
    environment:
      - DB_USER=gitlab
      - DB_PASS=x9fdwfwkmopbjk2hj9316cad69bs0v03
      - DB_NAME=gitlabdb

  gitlab:
    image: gitlab/gitlab-ce:11.6.0
    volumes:
      - /opt/docker/containers/integration/gitlab:/var/opt/gitlab
    environment:
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=x9fdwfwkmopbjk2hj9316cad69bs0v03
      - DB_NAME=gitlabdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false
      - GITLAB_HOST=localhost
      - GITLAB_PORT=80
      - GITLAB_SSH_PORT=22
      - GITLAB_RELATIVE_URL_ROOT=
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_ROOT_PASSWORD=nddsb2tze152m2dv8g8m4o19at5rjzsc

  networks:
    default:
      external:
        name: network-integration